
/*

--https://msbiskills.com/2015/05/08/t-sql-query-the-complex-week-puzzle/
*/
WITH CTE_S1 AS(


SELECT 
PRODUCTID,PRODUCTNAME,
ENDDATE,
CASE WHEN ENDDATE=DATEADD(DD,7,LAG(EndDate) OVER(ORDER BY ENDDATE)) THEN 0 ELSE 1 END FIL
FROM  ProductInfo
)
,CTE_S2 AS
(
SELECT *,SUM(FIL) OVER(ORDER BY ENDDATE) GRP FROM CTE_S1
)



,CTE_S3 AS(

SELECT PRODUCTID,PRODUCTNAME,GRP,
MAX(ENDDATE) ENDDATE FROM  CTE_S2
GROUP BY PRODUCTID,PRODUCTNAME,
GRP)

SELECT C2.PRODUCTID,C2.PRODUCTNAME,C2.ENDDATE ,C1.ENDDATE NEWDATE
FROM 
CTE_S3 C1
JOIN CTE_S2 C2
ON C1.GRP=C2.GRP

