/*
--https://msbiskills.com/2015/05/06/t-sql-query-the-consecutive-wins-puzzle-2/
*/
;WITH CTE1 AS(
SELECT * , ROW_NUMBER() OVER  (PARTITION BY PlayerId ORDER BY GameDate) rnk 
FROM GameResults )   

,CTE2 AS
(
SELECT TOURNAMENTID,PLAYERID,GAMEDATE,RESULT,RNK,1 AS CNT
FROM CTE1 WHERE  RNK=1
UNION ALL
SELECT C1.TOURNAMENTID,C1.PLAYERID,C1.GAMEDATE,C1.RESULT,C1.RNK,
CASE WHEN C2.RESULT=C1.RESULT THEN C2.CNT  ELSE C2.CNT+1 END CNT

FROM CTE2 C2
JOIN CTE1 C1
ON C1.PLAYERID=C2.PLAYERID 
AND C2.RNK+1=C1.RNK
)

,CTE3 AS(
SELECT PLAYERID,CNT,COUNT(CNT) GRP FROM CTE2 GROUP BY PLAYERID,CNT )

SELECT PLAYERID,MAX(GRP) CWINS FROM CTE3 GROUP BY PLAYERID

 
 
 
