/*
--https://msbiskills.com/2015/06/16/t-sql-query-the-total-values-missing-puzzle/

*/


WITH CTE_CNT AS 
(
SELECT MIN(COL1) ST_COL,MAX(COL1) END_COL FROM [findGaps2] 
UNION ALL
SELECT ST_COL+1,END_COL FROM CTE_CNT WHERE ST_COL+1<=END_COL
)
,CTE_N AS(
SELECT ISNULL(COL1,0) CNT,ST_COL 
FROM CTE_CNT C LEFT OUTER JOIN  [findGaps2] FG ON FG.COL1=C.ST_COL WHERE COL1 IS NULL)


SELECT COUNT(CNT) FROM CTE_N GROUP BY CNT