--SOL2 WITH DATE GEN
 ;WITH CTE_DT
 AS
 (
 SELECT MIN(DT) ST_DT,MAX(DT) ED_DT FROM [test]
 )
 ,CTE_DT_GEN AS
 (
 SELECT 
 ST_DT ,ED_DT FROM CTE_DT
 UNION ALL
 SELECT DATEADD(DAY,1,ST_DT) ST_DT,ED_DT FROM CTE_DT_GEN WHERE DATEADD(DAY,1,ST_DT)<=ED_DT
 )

 SELECT 
 ISNULL(T1.HOURSS,0) HOURSS,
 C1.ST_DT
 FROM CTE_DT_GEN C1
 LEFT JOIN [test] T1
 ON C1.ST_DT=T1.DT


 