/*
--https://msbiskills.com/2015/06/16/t-sql-query-the-gap-puzzle-puzzle-ii/

*/


WITH CTE_TAG_GAP AS(

SELECT
COL1,
CASE 
WHEN COL1+1<LEAD(COL1,1) OVER(ORDER BY COL1) THEN CONCAT('**',CAST(COL1 AS NVARCHAR(10)))
ELSE CAST(COL1 AS NVARCHAR(10)) END RCOL
FROM FindGaps2)
,CTE_FND_NO AS(
SELECT 
CASE WHEN LEFT(RCOL,2)='**' THEN COL1+1 END  BEGINSWITH,
CASE WHEN LEFT(RCOL,2)='**' THEN (LEAD(COL1,1) OVER(ORDER BY COL1))-1 END ENDSWITH
FROM CTE_TAG_GAP)

SELECT * FROM CTE_FND_NO WHERE (BEGINSWITH IS NOT NULL) AND (ENDSWITH IS NOT NULL)


