/*
--https://msbiskills.com/2016/06/13/sql-puzzle-generate-ids-puzzle/
GENERATE IDS

CREATE TABLE ID1(ID INT ,[NAME] VARCHAR(5))
CREATE TABLE ID2(ID INT ,[NAME] VARCHAR(5))

INSERT INTO ID1 VALUES(1,'AAA')
INSERT INTO ID1 VALUES(2,'AAA')
INSERT INTO ID1 VALUES(3,'AAA')

INSERT INTO ID2([NAME]) VALUES('BBB')
INSERT INTO ID2([NAME]) VALUES('BBB')
INSERT INTO ID2([NAME]) VALUES('BBB')
*/

--SOL1 WITH UNION ALL
WITH CTE AS(
SELECT ID,[NAME] FROM ID1
UNION ALL
SELECT ID,[NAME] FROM ID2
)

SELECT ROW_NUMBER() OVER(ORDER BY [NAME]) ID,[NAME] FROM CTE


--SOL2 
SELECT ROW_NUMBER() OVER(ORDER BY [NAME]) ID,[NAME] FROM(
SELECT ISNULL(I1.ID,I2.ID) ID,ISNULL(I1.[NAME],I2.[NAME]) [NAME] FROM ID1 I1 
FULL OUTER JOIN ID2 I2
ON I1.ID=ISNULL(I2.ID,0))PVT

