/*
--https://msbiskills.com/2016/06/30/sql-server-puzzle-hiring-years-puzzle/
*/


WITH CTE_DEPT AS(
SELECT 
DEPARTMENT_ID,
HIRE_DATE,
YEAR(HIRE_DATE) HIRE_YR,
ROW_NUMBER() OVER(PARTITION BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID) RNK
--RANK() OVER(PARTITION BY DEPARTMENT_ID  ORDER BY YEAR(HIRE_DATE) )
FROM [EMPLOYEES_N1]
)


SELECT 
DEPARTMENT_ID,
MIN(HIRE_YR) YEAR1,
CASE 
WHEN MAX(RNK)-MIN(RNK)>1 THEN CAST(CONCAT('MANY(',MAX(RNK)-MIN(RNK),')') AS NVARCHAR(10)) 
WHEN MAX(RNK)-MIN(RNK)=0 THEN ''
ELSE CAST(MAX(HIRE_YR) AS NVARCHAR(10))  END YEAR2
 FROM CTE_DEPT
 GROUP BY DEPARTMENT_ID