/*
--https://msbiskills.com/2015/10/21/sql-puzzle-find-every-saturday-and-their-corresponding-last-months-saturday-with-in-a-year/
*/

WITH CTE_DT AS(

SELECT DATEFROMPARTS(2012,1,1) STDATE , DATENAME(WEEKDAY,DATEFROMPARTS(2012,1,1) ) WD,MONTH(DATEFROMPARTS(2012,1,1)) MH
UNION ALL
SELECT DATEADD(DAY,1,STDATE) STDATE,DATENAME(WEEKDAY,DATEADD(DAY,1,STDATE) ) WD,MONTH(DATEADD(DAY,1,STDATE) ) MH FROM CTE_DT 
WHERE STDATE<DATEFROMPARTS(2012,12,31)
)

SELECT CASE WHEN MONTH((LAG(STDATE,4) OVER(ORDER BY MH)))=MONTH(STDATE) THEN NULL ELSE LAG(STDATE,4) OVER(ORDER BY MH) END PREV_SAT,
STDATE SAT
FROM CTE_DT WHERE WD='Saturday'
ORDER BY STDATE
OPTION(MAXRECURSION 0)

