/*
--https://msbiskills.com/2015/05/04/1151/

*/
;WITH CTE_DATES AS
(
SELECT 
* 
FROM PARTS CROSS JOIN DATES
)
SELECT C.PARTID,C.IDATE,CASE WHEN O.IDATE IS NULL THEN 0 ELSE COUNT(*) END CNT
FROM CTE_DATES C
LEFT OUTER JOIN ORDERS1 O
ON C.PARTID=O.PARTID AND C.IDATE=O.IDATE
GROUP BY C.PARTID,C.IDATE,O.IDATE
ORDER BY C.PARTID