/*
--https://msbiskills.com/2015/05/02/t-sql-query-the-non-zero-puzzle/
*/
WITH CTE_VAL AS (
SELECT * FROM ATABLE WHERE VALUE>0)

SELECT COALESCE(C.ID,B.ID) ID ,COALESCE(C.VALUE,B.VALUE) VALUE FROM CTE_VAL C
FULL OUTER JOIN 
(SELECT * FROM BTABLE WHERE ID NOT IN (SELECT ID FROM CTE_VAL)) B
ON C.ID=B.ID
ORDER BY COALESCE(C.ID,B.ID)

