/*
--https://msbiskills.com/2012/07/24/t-sql-7/
--windows function
*/

--SOL 1 RECURSIVE CTE
;WITH RUN_TOT AS
(
SELECT ID IDE,ID AS RTOT FROM LIST WHERE ID=1
UNION ALL
SELECT ID IDE,ID+RTOT as RTOT FROM LIST JOIN RUN_TOT ON LIST.ID=RUN_TOT.IDE+1 
)

SELECT * FROM RUN_TOT
--SOL 2
SELECT 
SUM(ID) OVER(ORDER BY ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) RUNTOT
FROM List

--SOL 3 USING CURSOR
DECLARE @TOT INT
DECLARE @RUN_TOT INT
SET @RUN_TOT=0
DECLARE RUN_TOT CURSOR FOR
SELECT * FROM LIST 
OPEN RUN_TOT
FETCH NEXT FROM RUN_TOT INTO @TOT
WHILE @@FETCH_STATUS=0
BEGIN
 
 SET @RUN_TOT=@TOT+@RUN_TOT
 PRINT @RUN_TOT
 FETCH NEXT FROM RUN_TOT INTO @TOT 

END

CLOSE RUN_TOT
DEALLOCATE RUN_TOT






