/*
--https://msbiskills.com/2015/03/22/t-sql-query-gold-rate-puzzle/
*/
WITH CTE1 AS(

SELECT RATE,DT ,ISNULL(LAG(DT) OVER(PARTITION BY RATE ORDER BY DT),DT) MINDT FROM testGoldRateChange 
)

,CTE2 AS(
SELECT 
DT,
RATE,
CASE WHEN DATEDIFF(DD,MINDT,DT)=1 THEN 0 ELSE DATEDIFF(DD,MINDT,DT) END DIFDT
FROM CTE1)

SELECT MIN(DT) START_DATE,MAX(DT) END_DATE,RATE 
FROM CTE2 GROUP BY RATE,DIFDT

