/*
--https://msbiskills.com/2015/03/31/t-sql-query-the-all-products-puzzle/
*/
WITH CTE_ST1 AS(
SELECT ID,SM.PRODUCTNAME,S.SALEID,S.CUSTID,S.SALEDATE FROM SpecialProductMaster SM
JOIN SALES S ON
SM.PRODUCTNAME=S.PRODUCTNAME)


SELECT * FROM SALES WHERE CUSTID IN(
SELECT DISTINCT CUSTID  FROM CTE_ST1 GROUP BY CUSTID HAVING COUNT(*)>1)
AND PRODUCTNAME IN(SELECT PRODUCTNAME FROM SpecialProductMaster)

