/*
--https://msbiskills.com/2015/03/31/t-sql-query-the-deal-puzzle/
*/
WITH CTE_DL AS(

SELECT RANK() OVER(ORDER BY PRICE,QUANTITY) GRP,
DEAL_ID,PRICE,
QUANTITY,
CAST(CONTRACT_MONTH AS DATETIME) CONTRACT_MONTH,
TOTAL_QUANTITY FROM deal_details
)

,CTE_DL1 AS(
SELECT 
*,
CASE WHEN ISNULL(LAG(PRICE) OVER(ORDER BY CONTRACT_MONTH) ,PRICE)= PRICE THEN 
GRP
ELSE
GRP*100*RAND() END LST
FROM CTE_DL)

SELECT
MAX(DEAL_ID) DEAL_ID,
MAX(PRICE) PRICE,
MIN(CONTRACT_MONTH) START_MONTH,
MAX(CONTRACT_MONTH) END_MONTH,
SUM(TOTAL_QUANTITY) TOTAL_QUANTITY
FROM CTE_DL1 
GROUP BY LST
ORDER BY START_MONTH