/*
--https://msbiskills.com/2015/03/23/t-sql-query-the-candidate-joining-puzzle/
*/
--SOL 1
WITH CTE_HOL AS(
SELECT ID,HOLIDAYDATE,ISNULL(DATEDIFF(DD,LAG(HOLIDAYDATE) OVER(ORDER BY HOLIDAYDATE),HOLIDAYDATE),1) CNT
 FROM HOLIDAYS)

 
 ,CTE_HOL2 AS(
 SELECT MIN(HOLIDAYDATE) STDATE,MAX(HOLIDAYDATE) ENDDATE
 FROM CTE_HOL GROUP BY CNT)
 

 SELECT CID,CJoiningDate,
 ISNULL(DATEADD(DD,
 CASE WHEN DATEDIFF(DD,ENDDATE,STDATE)=0 THEN -1
 ELSE
 DATEDIFF(DD,ENDDATE,STDATE) END,STDATE),CJoiningDate) VALIDJOININGDATE
  FROM  CandidateJoining 
 LEFT OUTER JOIN CTE_HOL2 H1
 ON H1.STDATE=CJoiningDate OR H1.ENDDATE=CJoiningDate

 