/*
--https://msbiskills.com/2015/03/31/t-sql-query-all-items-puzzle/
*/
;WITH CTE_CUST AS
(
SELECT CUST_NO,ITEM_NO FROM ITEM
CROSS JOIN (SELECT DISTINCT CUST_NO FROM ORDERED)A
)

SELECT 
ISNULL(O.CUST_NO,C1.CUST_NO) CUST_NO,ISNULL(O.ITEM_NO,C1.ITEM_NO) ITEM_NO,ISNULL(QTY_ORDERED,0) QTY_ORDERED
FROM 
CTE_CUST C1 
LEFT OUTER JOIN
ORDERED O ON
O.CUST_NO=C1.CUST_NO AND O.ITEM_NO=C1.ITEM_NO
ORDER BY ISNULL(O.ITEM_NO,C1.ITEM_NO),ISNULL(O.CUST_NO,C1.CUST_NO)