/*
--https://msbiskills.com/2012/07/24/t-sql-6/

*/
--SOL 1
SELECT DISTINCT
ID,
ISNULL(NAME,(SELECT TOP 1 NAME FROM PQ P1 WHERE P1.NAME IS NOT NULL AND  P1.ID=P.ID)) NAME,
ISNULL(TYPED,(SELECT TOP 1 TYPED FROM PQ P2 WHERE P2.TYPED IS NOT NULL AND  P2.ID=P.ID)) TYPED
FROM PQ P

--SOL 2
SELECT
ID,
MAX(NAME) NAME,
MAX(TYPED) TYPED
FROM PQ
GROUP BY ID

