/*
--https://msbiskills.com/2015/04/11/t-sql-query-how-many-workweek-days-in-date-range-puzzle/
*/
DECLARE @st AS DATETIME = '06/01/2017'
DECLARE @Et AS DATETIME = '06/30/2017'
DECLARE @WKENDCNT INT
SET @WKENDCNT=0
;WITH CTE_DT AS(
SELECT @st STRAT_DATE,DATEADD(DD,1,@st) NXT_DAY,1 AS NDAY,0 AS NOOFDAY,
CASE WHEN
((DATENAME(DW,@st)='SATURDAY') OR (DATENAME(DW,@st)='SUNDAY')) THEN 
 1 ELSE 0 END  CNT
UNION ALL
SELECT @st STRAT_DATE,DATEADD(DD,1,NXT_DAY) NXT_DAY,NDAY+1 NDAY,(NDAY+1)-CNT NOOFDAY,
CASE WHEN
((DATENAME(DW,NXT_DAY)='SATURDAY') OR (DATENAME(DW,NXT_DAY)='SUNDAY')) THEN 
 CNT+1 ELSE CNT END  CNT
 FROM CTE_DT WHERE NXT_DAY<= @Et
 )

 SELECT MAX(NOOFDAY) CNTWKDAYS FROM CTE_DT 
