/*
--https://msbiskills.com/2015/04/02/t-sql-query-finding-the-missing-gaps-puzzle/
*/
WITH CTE_GAP AS(
SELECT CASE 
WHEN (LEAD(NUM) OVER(ORDER BY NUM)- NUM )>1 THEN
NUM+1
END GAPSTART,
CASE 
WHEN (LEAD(NUM) OVER(ORDER BY NUM)- NUM )>1 THEN
((LEAD(NUM) OVER(ORDER BY NUM)- NUM )-1)+NUM
END ENDSTART
FROM findGaps)

SELECT * FROM CTE_GAP 
WHERE GAPSTART IS NOT NULL OR ENDSTART IS NOT NULL
