/*
--REVERSE A STRING WITHOUT USING REVERSE FUNCTION.
--SOLUTION 1 USES RECURSIVE CTE.
--https://msbiskills.com/2016/06/13/sql-puzzle-reverse-a-string-without-using-reverse-function-recursive-cte-while-loop/
*/

DECLARE @STR AS NVARCHAR(20)='SUMOJIT'

;WITH CTE AS
(
SELECT CAST(RIGHT(@STR,1) AS NVARCHAR(20)) STR_SPT ,LEN(@STR) TOT_LEN, CAST(1 AS INT) AS CNT
UNION ALL
SELECT CAST(CONCAT(C.STR_SPT,SUBSTRING(@STR,(C.TOT_LEN-1),1))AS NVARCHAR(20)) STR_SPT,LEN(@STR)-CNT TOT_LEN, CAST(CNT+1 AS INT) AS CNT
FROM CTE C
WHERE CNT<LEN(@STR)
)

SELECT STR_SPT FROM CTE WHERE CNT=LEN(@STR)

--SOLUTION 2 USES NUMBER TABLE

DECLARE @STR AS NVARCHAR(20)='SUMOJIT NATH'
DECLARE @STR_REV NVARCHAR(20)=''
;WITH CTE AS(
SELECT 
SUBSTRING(@STR,LEN(@STR)-NUMBER,1) ST
FROM 
(
SELECT
DISTINCT NUMBER 
FROM
MASTER..SPT_VALUES
WHERE
NUMBER >= 0 AND NUMBER<=LEN(@STR)
)PV)
SELECT @STR_REV=@STR_REV+ST FROM CTE 
SELECT @STR_REV