/*
--https://msbiskills.com/2015/10/08/sql-puzzle-sum-of-digits-puzzle/
*/


DECLARE @ST_TAB TABLE
(
ST NVARCHAR(6)
)
INSERT INTO @ST_TAB SELECT '100992'
--SET @ST='1WW992'-- or '1WW992' '100992'

;WITH CTE_CAL AS
(

SELECT CAST(SUBSTRING(ST,1,1) AS NVARCHAR(6)) ST,1 AS POS,LEN(ST) AS L FROM @ST_TAB

UNION ALL

SELECT CAST(( CASE WHEN SUBSTRING(S.ST , POS+1,1) LIKE '[A-Z]' THEN '0' ELSE SUBSTRING(S.ST , POS+1,1) END) AS NVARCHAR(6) ) ST,POS+1 POS,L
FROM @ST_TAB S JOIN CTE_CAL C ON C.ST<>S.ST AND C.POS<C.L

)

SELECT SUM(CAST(ST AS INT)) totol FROM CTE_CAL

