
/*
CREATE TABLE TABLE1(ID INT ,[NAME] VARCHAR(10))
CREATE TABLE TABLE2(ID INT ,[NAME] VARCHAR(10))
CREATE TABLE TABLE3(ID INT ,[NAME] VARCHAR(10))

INSERT INTO TABLE1 VALUES(1,'Pawan'),
(2,'Sharlee'),
(3,'Rahisha'),
(4,'Disha'),
(5,'Ramesh'),
(6,'Kishan'),
(7,	'Qoutilya'),
(8,'Sandeep')

INSERT INTO TABLE2 VALUES(1,'Diljit'),
(2,'Kumar'),
(3,'Khowal')

INSERT INTO TABLE3 VALUES(1	,'MSBISKILLS'),
(6,'MSBI')
*/

--SOL1 USING COALESCE AND FULL OUTER JOIN.
SELECT 
T1.ID,COALESCE(T3.NAME,T2.NAME,T1.NAME) [NAME]
FROM TABLE1 T1
FULL OUTER JOIN
TABLE2 T2
ON T1.ID=T2.ID
FULL OUTER JOIN TABLE3 T3
ON T1.ID=T3.ID


